/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionRouteImport } from './routes/action'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ItineraryRouteImport } from './routes/itinerary'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as LockerRouteImport } from './routes/locker'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as MoreRouteImport } from './routes/more'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PairingsRouteImport } from './routes/pairings'
import { Route as RecapsRouteImport } from './routes/recaps'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ScoresRouteImport } from './routes/scores'
import { Route as SethRouteImport } from './routes/seth'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SkinsRouteImport } from './routes/skins'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as MomIndexRouteImport } from './routes/mom.index'
import { Route as MomEmailsRouteImport } from './routes/mom.emails'
import { Route as MomPairingsRouteImport } from './routes/mom.pairings'
import { Route as MomPlayersRouteImport } from './routes/mom.players'
import { Route as PlayersIndexRouteImport } from './routes/players.index'
import { Route as PlayersSlugRouteImport } from './routes/players.$slug'
import { Route as SethIndexRouteImport } from './routes/seth.index'
import { Route as SethCoursesRouteImport } from './routes/seth.courses'
import { Route as SethEmailsRouteImport } from './routes/seth.emails'
import { Route as SethPairingsRouteImport } from './routes/seth.pairings'
import { Route as SethPlayersRouteImport } from './routes/seth.players'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionRoute = ActionRouteImport.update({
  id: '/action',
  path: '/action',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryRoute = ItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const LockerRoute = LockerRouteImport.update({
  id: '/locker',
  path: '/locker',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PairingsRoute = PairingsRouteImport.update({
  id: '/pairings',
  path: '/pairings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapsRoute = RecapsRouteImport.update({
  id: '/recaps',
  path: '/recaps',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresRoute = ScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const SethRoute = SethRouteImport.update({
  id: '/seth',
  path: '/seth',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SkinsRoute = SkinsRouteImport.update({
  id: '/skins',
  path: '/skins',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MomIndexRoute = MomIndexRouteImport.update({
  id: '/mom/',
  path: '/mom/',
  getParentRoute: () => rootRouteImport,
} as any)
const MomEmailsRoute = MomEmailsRouteImport.update({
  id: '/mom/emails',
  path: '/mom/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const MomPairingsRoute = MomPairingsRouteImport.update({
  id: '/mom/pairings',
  path: '/mom/pairings',
  getParentRoute: () => rootRouteImport,
} as any)
const MomPlayersRoute = MomPlayersRouteImport.update({
  id: '/mom/players',
  path: '/mom/players',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersSlugRoute = PlayersSlugRouteImport.update({
  id: '/players/$slug',
  path: '/players/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SethIndexRoute = SethIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SethRoute,
} as any)
const SethCoursesRoute = SethCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => SethRoute,
} as any)
const SethEmailsRoute = SethEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => SethRoute,
} as any)
const SethPairingsRoute = SethPairingsRouteImport.update({
  id: '/pairings',
  path: '/pairings',
  getParentRoute: () => SethRoute,
} as any)
const SethPlayersRoute = SethPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => SethRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/action': typeof ActionRoute
  '/evidence': typeof EvidenceRoute
  '/flights': typeof FlightsRoute
  '/history': typeof HistoryRoute
  '/itinerary': typeof ItineraryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/ledger': typeof LedgerRoute
  '/locker': typeof LockerRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/pairings': typeof PairingsRoute
  '/recaps': typeof RecapsRoute
  '/results': typeof ResultsRoute
  '/scores': typeof ScoresRoute
  '/seth': typeof SethRouteWithChildren
  '/settings': typeof SettingsRoute
  '/skins': typeof SkinsRoute
  '/stats': typeof StatsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/mom/emails': typeof MomEmailsRoute
  '/mom/pairings': typeof MomPairingsRoute
  '/mom/players': typeof MomPlayersRoute
  '/players/$slug': typeof PlayersSlugRoute
  '/seth/courses': typeof SethCoursesRoute
  '/seth/emails': typeof SethEmailsRoute
  '/seth/pairings': typeof SethPairingsRoute
  '/seth/players': typeof SethPlayersRoute
  '/mom/': typeof MomIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/seth/': typeof SethIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/action': typeof ActionRoute
  '/evidence': typeof EvidenceRoute
  '/flights': typeof FlightsRoute
  '/history': typeof HistoryRoute
  '/itinerary': typeof ItineraryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/ledger': typeof LedgerRoute
  '/locker': typeof LockerRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/pairings': typeof PairingsRoute
  '/recaps': typeof RecapsRoute
  '/results': typeof ResultsRoute
  '/scores': typeof ScoresRoute
  '/settings': typeof SettingsRoute
  '/skins': typeof SkinsRoute
  '/stats': typeof StatsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/mom/emails': typeof MomEmailsRoute
  '/mom/pairings': typeof MomPairingsRoute
  '/mom/players': typeof MomPlayersRoute
  '/players/$slug': typeof PlayersSlugRoute
  '/seth/courses': typeof SethCoursesRoute
  '/seth/emails': typeof SethEmailsRoute
  '/seth/pairings': typeof SethPairingsRoute
  '/seth/players': typeof SethPlayersRoute
  '/mom': typeof MomIndexRoute
  '/players': typeof PlayersIndexRoute
  '/seth': typeof SethIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/action': typeof ActionRoute
  '/evidence': typeof EvidenceRoute
  '/flights': typeof FlightsRoute
  '/history': typeof HistoryRoute
  '/itinerary': typeof ItineraryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/ledger': typeof LedgerRoute
  '/locker': typeof LockerRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/pairings': typeof PairingsRoute
  '/recaps': typeof RecapsRoute
  '/results': typeof ResultsRoute
  '/scores': typeof ScoresRoute
  '/seth': typeof SethRouteWithChildren
  '/settings': typeof SettingsRoute
  '/skins': typeof SkinsRoute
  '/stats': typeof StatsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/mom/emails': typeof MomEmailsRoute
  '/mom/pairings': typeof MomPairingsRoute
  '/mom/players': typeof MomPlayersRoute
  '/players/$slug': typeof PlayersSlugRoute
  '/seth/courses': typeof SethCoursesRoute
  '/seth/emails': typeof SethEmailsRoute
  '/seth/pairings': typeof SethPairingsRoute
  '/seth/players': typeof SethPlayersRoute
  '/mom/': typeof MomIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/seth/': typeof SethIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/action'
    | '/evidence'
    | '/flights'
    | '/history'
    | '/itinerary'
    | '/leaderboard'
    | '/ledger'
    | '/locker'
    | '/login'
    | '/matches'
    | '/more'
    | '/notifications'
    | '/pairings'
    | '/recaps'
    | '/results'
    | '/scores'
    | '/seth'
    | '/settings'
    | '/skins'
    | '/stats'
    | '/courses/$slug'
    | '/invite/$token'
    | '/mom/emails'
    | '/mom/pairings'
    | '/mom/players'
    | '/players/$slug'
    | '/seth/courses'
    | '/seth/emails'
    | '/seth/pairings'
    | '/seth/players'
    | '/mom/'
    | '/players/'
    | '/seth/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/action'
    | '/evidence'
    | '/flights'
    | '/history'
    | '/itinerary'
    | '/leaderboard'
    | '/ledger'
    | '/locker'
    | '/login'
    | '/matches'
    | '/more'
    | '/notifications'
    | '/pairings'
    | '/recaps'
    | '/results'
    | '/scores'
    | '/settings'
    | '/skins'
    | '/stats'
    | '/courses/$slug'
    | '/invite/$token'
    | '/mom/emails'
    | '/mom/pairings'
    | '/mom/players'
    | '/players/$slug'
    | '/seth/courses'
    | '/seth/emails'
    | '/seth/pairings'
    | '/seth/players'
    | '/mom'
    | '/players'
    | '/seth'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/action'
    | '/evidence'
    | '/flights'
    | '/history'
    | '/itinerary'
    | '/leaderboard'
    | '/ledger'
    | '/locker'
    | '/login'
    | '/matches'
    | '/more'
    | '/notifications'
    | '/pairings'
    | '/recaps'
    | '/results'
    | '/scores'
    | '/seth'
    | '/settings'
    | '/skins'
    | '/stats'
    | '/courses/$slug'
    | '/invite/$token'
    | '/mom/emails'
    | '/mom/pairings'
    | '/mom/players'
    | '/players/$slug'
    | '/seth/courses'
    | '/seth/emails'
    | '/seth/pairings'
    | '/seth/players'
    | '/mom/'
    | '/players/'
    | '/seth/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionRoute: typeof ActionRoute
  EvidenceRoute: typeof EvidenceRoute
  FlightsRoute: typeof FlightsRoute
  HistoryRoute: typeof HistoryRoute
  ItineraryRoute: typeof ItineraryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LedgerRoute: typeof LedgerRoute
  LockerRoute: typeof LockerRoute
  LoginRoute: typeof LoginRoute
  MatchesRoute: typeof MatchesRoute
  MoreRoute: typeof MoreRoute
  NotificationsRoute: typeof NotificationsRoute
  PairingsRoute: typeof PairingsRoute
  RecapsRoute: typeof RecapsRoute
  ResultsRoute: typeof ResultsRoute
  ScoresRoute: typeof ScoresRoute
  SethRoute: typeof SethRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SkinsRoute: typeof SkinsRoute
  StatsRoute: typeof StatsRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
  MomEmailsRoute: typeof MomEmailsRoute
  MomPairingsRoute: typeof MomPairingsRoute
  MomPlayersRoute: typeof MomPlayersRoute
  PlayersSlugRoute: typeof PlayersSlugRoute
  MomIndexRoute: typeof MomIndexRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action': {
      id: '/action'
      path: '/action'
      fullPath: '/action'
      preLoaderRoute: typeof ActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary': {
      id: '/itinerary'
      path: '/itinerary'
      fullPath: '/itinerary'
      preLoaderRoute: typeof ItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locker': {
      id: '/locker'
      path: '/locker'
      fullPath: '/locker'
      preLoaderRoute: typeof LockerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pairings': {
      id: '/pairings'
      path: '/pairings'
      fullPath: '/pairings'
      preLoaderRoute: typeof PairingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recaps': {
      id: '/recaps'
      path: '/recaps'
      fullPath: '/recaps'
      preLoaderRoute: typeof RecapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores': {
      id: '/scores'
      path: '/scores'
      fullPath: '/scores'
      preLoaderRoute: typeof ScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seth': {
      id: '/seth'
      path: '/seth'
      fullPath: '/seth'
      preLoaderRoute: typeof SethRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skins': {
      id: '/skins'
      path: '/skins'
      fullPath: '/skins'
      preLoaderRoute: typeof SkinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mom/': {
      id: '/mom/'
      path: '/mom'
      fullPath: '/mom/'
      preLoaderRoute: typeof MomIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mom/emails': {
      id: '/mom/emails'
      path: '/mom/emails'
      fullPath: '/mom/emails'
      preLoaderRoute: typeof MomEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mom/pairings': {
      id: '/mom/pairings'
      path: '/mom/pairings'
      fullPath: '/mom/pairings'
      preLoaderRoute: typeof MomPairingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mom/players': {
      id: '/mom/players'
      path: '/mom/players'
      fullPath: '/mom/players'
      preLoaderRoute: typeof MomPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$slug': {
      id: '/players/$slug'
      path: '/players/$slug'
      fullPath: '/players/$slug'
      preLoaderRoute: typeof PlayersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seth/': {
      id: '/seth/'
      path: '/'
      fullPath: '/seth/'
      preLoaderRoute: typeof SethIndexRouteImport
      parentRoute: typeof SethRoute
    }
    '/seth/courses': {
      id: '/seth/courses'
      path: '/courses'
      fullPath: '/seth/courses'
      preLoaderRoute: typeof SethCoursesRouteImport
      parentRoute: typeof SethRoute
    }
    '/seth/emails': {
      id: '/seth/emails'
      path: '/emails'
      fullPath: '/seth/emails'
      preLoaderRoute: typeof SethEmailsRouteImport
      parentRoute: typeof SethRoute
    }
    '/seth/pairings': {
      id: '/seth/pairings'
      path: '/pairings'
      fullPath: '/seth/pairings'
      preLoaderRoute: typeof SethPairingsRouteImport
      parentRoute: typeof SethRoute
    }
    '/seth/players': {
      id: '/seth/players'
      path: '/players'
      fullPath: '/seth/players'
      preLoaderRoute: typeof SethPlayersRouteImport
      parentRoute: typeof SethRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SethRouteChildren {
  SethCoursesRoute: typeof SethCoursesRoute
  SethEmailsRoute: typeof SethEmailsRoute
  SethPairingsRoute: typeof SethPairingsRoute
  SethPlayersRoute: typeof SethPlayersRoute
  SethIndexRoute: typeof SethIndexRoute
}

const SethRouteChildren: SethRouteChildren = {
  SethCoursesRoute: SethCoursesRoute,
  SethEmailsRoute: SethEmailsRoute,
  SethPairingsRoute: SethPairingsRoute,
  SethPlayersRoute: SethPlayersRoute,
  SethIndexRoute: SethIndexRoute,
}

const SethRouteWithChildren = SethRoute._addFileChildren(SethRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionRoute: ActionRoute,
  EvidenceRoute: EvidenceRoute,
  FlightsRoute: FlightsRoute,
  HistoryRoute: HistoryRoute,
  ItineraryRoute: ItineraryRoute,
  LeaderboardRoute: LeaderboardRoute,
  LedgerRoute: LedgerRoute,
  LockerRoute: LockerRoute,
  LoginRoute: LoginRoute,
  MatchesRoute: MatchesRoute,
  MoreRoute: MoreRoute,
  NotificationsRoute: NotificationsRoute,
  PairingsRoute: PairingsRoute,
  RecapsRoute: RecapsRoute,
  ResultsRoute: ResultsRoute,
  ScoresRoute: ScoresRoute,
  SethRoute: SethRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SkinsRoute: SkinsRoute,
  StatsRoute: StatsRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
  MomEmailsRoute: MomEmailsRoute,
  MomPairingsRoute: MomPairingsRoute,
  MomPlayersRoute: MomPlayersRoute,
  PlayersSlugRoute: PlayersSlugRoute,
  MomIndexRoute: MomIndexRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
